const FINAL_SIMULACRO_QUESTIONS = [
  // --- 1. Fundamentos & Sintaxis ---
  { q: "¿Cuál de las siguientes declaraciones de variable es válida en Java?",
    opts: ["int 1numero = 10;", "double valor-total = 5.5;", "String _nombre = \"Java\";", "char letra = 'abc';"], ans: 2,
    exp: "Los identificadores no pueden empezar por número ni contener guiones. char solo admite un carácter entre comillas simples." },
  { q: "Dado el código: int x = 5; int y = x++; ¿Qué valores tienen x e y tras la ejecución?",
    opts: ["x=5, y=5", "x=6, y=5", "x=6, y=6", "x=5, y=6"], ans: 1,
    exp: "x++ es un post-incremento: primero se asigna el valor actual de x a y (5) y luego x aumenta a 6." },
  { q: "¿Qué resultado produce la expresión (int) (7.9 / 2)?",
    opts: ["3.95", "4", "3", "3.5"], ans: 2,
    exp: "7.9 / 2 = 3.95. Al hacer el cast a int, se trunca la parte decimal, quedando 3." },
  { q: "¿Cuál es el valor por defecto de un atributo de tipo boolean en una clase?",
    opts: ["true", "false", "null", "0"], ans: 1,
    exp: "En Java, los atributos booleanos se inicializan por defecto a false." },
  { q: "¿Qué operador se utiliza para comparar si dos variables primitivas son iguales?",
    opts: ["=", "==", ".equals()", "is"], ans: 1,
    exp: "== compara valores en primitivos. .equals() se usa para comparar el contenido de objetos (como String)." },

  // --- 2. POO Básica & Encapsulación ---
  { q: "¿Qué palabra clave se usa para llamar a un constructor de la misma clase desde otro constructor?",
    opts: ["super()", "this()", "new()", "id()"], ans: 1,
    exp: "this() permite la sobrecarga de constructores dentro de la misma clase." },
  { q: "Si un atributo es 'private', ¿desde dónde es accesible?",
    opts: ["Desde cualquier clase del proyecto", "Desde subclases únicamente", "Solo desde la propia clase", "Desde el mismo paquete"], ans: 2,
    exp: "private restringe la visibilidad al ámbito de la clase donde se define." },
  { q: "¿Qué ocurre si no definimos ningún constructor en nuestra clase?",
    opts: ["Error de compilación", "Java crea un constructor por defecto sin parámetros", "No se podrán crear objetos de esa clase", "Los atributos no se inicializarán"], ans: 1,
    exp: "Java inserta automáticamente un constructor vacío si no hay ninguno definido." },
  { q: "¿Cuál es la función de un método 'static'?",
    opts: ["Solo puede llamarse tras crear un objeto", "Pertenece a la clase y puede llamarse sin instanciar objetos", "Impide que el método sea sobreescrito", "Permite que el método sea accedido desde otros paquetes"], ans: 1,
    exp: "static indica que el miembro es de clase, no de instancia." },
  { q: "En el diseño de clases, ¿qué es la encapsulación?",
    opts: ["Heredar de múltiples padres", "Ocultar los datos (private) y exponer servicios (public)", "Usar solo métodos abstractos", "Convertir objetos en bytes"], ans: 1,
    exp: "Protege el estado interno del objeto y obliga a usar getters/setters." },

  // --- 3. Herencia & Polimorfismo (Code Analysis) ---
  { q: "Analiza:\nclass A { void x() { System.out.print(\"1\"); } }\nclass B extends A { void x() { System.out.print(\"2\"); } }\nA obj = new B();\nobj.x();\n¿Qué imprime?",
    opts: ["1", "2", "Error de compilación", "Nada"], ans: 1,
    exp: "Polimorfismo dinámico: en tiempo de ejecución se usa el método de la clase real del objeto (B)." },
  { q: "¿Qué debe ser la primera línea de un constructor en una clase hija?",
    opts: ["super() (o llamada al padre)", "this.atributo = valor;", "@Override", "package ...;"], ans: 0,
    exp: "Java exige construir la parte del padre antes que la del hijo." },
  { q: "¿Qué palabra clave impide que una clase sea heredada?",
    opts: ["abstract", "static", "final", "private"], ans: 2,
    exp: "Una clase final es una 'hoja' en el árbol de herencia." },
  { q: "Si la clase Perro hereda de Animal, ¿cuál es una asignación polimórfica válida?",
    opts: ["Perro p = new Animal();", "Animal a = new Perro();", "Perro p = (Animal) new Perro();", "Ninguna"], ans: 1,
    exp: "Una variable del tipo padre puede apuntar a cualquier objeto hijo." },
  { q: "¿Qué anotación se usa para indicar que estamos redefiniendo un método del padre?",
    opts: ["@Inherit", "@Overload", "@Override", "@Super"], ans: 2,
    exp: "@Override ayuda al compilador a verificar que la firma coincida con la del padre." },
  { q: "Analiza:\nclass P { int n=1; }\nclass H extends P { int n=2; }\nP obj = new H();\nSystem.out.print(obj.n);\n¿Qué imprime?",
    opts: ["1", "2", "Error", "null"], ans: 0,
    exp: "Los atributos NO tienen polimorfismo. Se accede al atributo del tipo de la variable (P)." },
  { q: "¿Qué ocurre si una subclase no sobrescribe un método abstracto de su padre?",
    opts: ["Funciona normalmente", "El método del padre se borra", "La subclase también debe ser declarada abstracta o dará error", "Se usa una implementación por defecto"], ans: 2,
    exp: "Las clases concretas están obligadas a implementar todos los métodos abstractos heredados." },
  { q: "¿Puede un método static ser @Override?",
    opts: ["Sí, siempre", "No, los métodos estáticos no se heredan con polimorfismo", "Solo si son public", "Solo en interfaces"], ans: 1,
    exp: "El polimorfismo solo aplica a métodos de instancia." },
  { q: "¿Qué visibilidad permite que un atributo sea visto por las clases hijas pero no por el resto del mundo (fuera del paquete)?",
    opts: ["private", "public", "protected", "default"], ans: 2,
    exp: "protected es el nivel intermedio diseñado para la herencia." },
  { q: "Dado: class X { X(int n){} }. ¿Qué pasa con class Y extends X { Y(){} }?",
    opts: ["Compila bien", "Error: X no tiene constructor por defecto y el de Y no llama a super(n)", "Funciona si n es 0", "X se inicializa solo"], ans: 1,
    exp: "Si el padre no tiene constructor vacío, el hijo DEBE llamar explícitamente a un constructor del padre con super(...)." },

  // --- 4. Interfaces & Abstracción ---
  { q: "¿Cuál es la principal diferencia entre Interface y Clase Abstracta?",
    opts: ["No hay diferencia", "La interfaz no puede tener atributos de instancia ni constructores", "La clase abstracta permite herencia múltiple", "Las interfaces se heredan con extends"], ans: 1,
    exp: "Las interfaces definen comportamiento puro (contratos). Las clases abstractas pueden tener estado y lógica base." },
  { q: "¿Qué modificador de acceso tienen los métodos de una interfaz por defecto en Java?",
    opts: ["private", "protected", "public", "default"], ans: 2,
    exp: "Los métodos de una interfaz son siempre públicos y abstractos (salvo default methods)." },
  { q: "¿Cuántas interfaces puede implementar una sola clase en Java?",
    opts: ["Solo una", "Máximo dos", "Ilimitadas", "Ninguna"], ans: 2,
    exp: "Java permite implementación múltiple de interfaces, pero solo herencia simple de clases." },
  { q: "¿Puede una clase abstracta implementar una interfaz?",
    opts: ["No", "Sí, y no está obligada a implementar sus métodos si ella misma es abstracta", "Sí, pero debe implementar todo inmediatamente", "Solo si la interfaz es vacía"], ans: 1,
    exp: "Las clases abstractas pueden delegar la implementación a sus hijas concretas." },
  { q: "¿Qué palabra clave se usa para que una clase use una interfaz?",
    opts: ["extends", "implements", "uses", "with"], ans: 1,
    exp: "extends para heredar clases, implements para cumplir interfaces." },

  // --- 5. Excepciones ---
  { q: "¿Qué bloque se ejecuta SIEMPRE al final de un try-catch, ocurra o no un error?",
    opts: ["finally", "end", "stop", "finish"], ans: 0,
    exp: "finally se usa para limpieza de recursos (cerrar ficheros, etc.)." },
  { q: "¿Cuál es la diferencia entre Checked y Unchecked exceptions?",
    opts: ["No hay diferencia real", "Checked obligan al programador a gestionarlas (try-catch o throws); Unchecked no", "Unchecked son más graves", "Checked solo ocurren en red"], ans: 1,
    exp: "Checked (Exception) se verifican en compilación. Unchecked (RuntimeException) en ejecución." },
  { q: "¿Para qué sirve la palabra 'throws' en la firma de un método?",
    opts: ["Lanza una excepción inmediatamente", "Indica que el método puede lanzar esa excepción y delega su gestión", "Captura el error", "Cierra el programa"], ans: 1,
    exp: "Es un aviso para quien llame al método: 'atrapa este error o pásalo'." },
  { q: "¿Qué clase es la raíz de todas las excepciones?",
    opts: ["Object", "Error", "Throwable", "Exception"], ans: 2,
    exp: "Throwable es la superclase de la que cuelgan Error y Exception." },
  { q: "Si intentas acceder a un objeto que es 'null', ¿qué excepción se lanza?",
    opts: ["ArrayIndexOutOfBoundsException", "NullPointerException", "IllegalArgumentException", "IOException"], ans: 1,
    exp: "Ocurre cuando llamas a un método o atributo de una referencia que no apunta a nada." },

  // --- 6. Colecciones & Estructuras Dinámicas ---
  { q: "¿Cuál es la principal ventaja de un ArrayList frente a un array convencional?",
    opts: ["Es más rápido", "Ocupa menos memoria", "Su tamaño es dinámico y crece automáticamente", "Puede guardar primitivos directamente"], ans: 2,
    exp: "Los arrays tienen tamaño fijo al crearse; los ArrayList gestionan su capacidad internamente." },
  { q: "¿Qué colección NO permite elementos duplicados?",
    opts: ["ArrayList", "LinkedList", "HashSet (Set)", "Vector"], ans: 2,
    exp: "Los Set (conjuntos) garantizan la unicidad de sus elementos." },
  { q: "¿Qué estructura de datos almacena pares clave-valor?",
    opts: ["List", "Set", "Map", "Queue"], ans: 2,
    exp: "HashMap o TreeMap asocian una clave única a un valor." },
  { q: "¿Qué método se usa para obtener el número de elementos en un ArrayList?",
    opts: ["length", "length()", "size()", "count()"], ans: 2,
    exp: "size() es el método estándar para colecciones. length es para arrays." },
  { q: "Si quieres asegurar que los elementos de tu lista estén ordenados automáticamente, ¿qué usarías?",
    opts: ["HashSet", "ArrayList", "TreeSet", "Stack"], ans: 2,
    exp: "Los 'Tree' (TreeSet, TreeMap) mantienen el orden natural o uno definido por un Comparator." },

  // --- 7. Casos Prácticos & Miscelánea ---
  { q: "¿Qué es la 'Firma' de un método?",
    opts: ["Su nombre únicamente", "Su nombre y su lista de parámetros", "Su tipo de retorno y nombre", "Su visibilidad"], ans: 1,
    exp: "Java distingue métodos por su nombre y el tipo/orden de sus argumentos (Sobrecarga)." },
  { q: "¿Qué comando se usa en la terminal para compilar un archivo Java?",
    opts: ["java MiClase.java", "javac MiClase.java", "run java MiClase", "compile MiClase"], ans: 1,
    exp: "javac (Java Compiler) genera el .class (bytecode)." },
  { q: "¿Cuál es el punto de entrada de cualquier aplicación Java ejecutable?",
    opts: ["El constructor de la clase principal", "public static void main(String[] args)", "El método start()", "init()"], ans: 1,
    exp: "La JVM busca exactamente esa firma para iniciar la ejecución." },
  { q: "¿Qué permite la 'genericidad' (<T>) en las colecciones?",
    opts: ["Que el programa sea más rápido", "Seguridad de tipos en compilación, evitando castings manuales", "Que la lista sea infinita", "Poder guardar solo números"], ans: 1,
    exp: "ArrayList<String> asegura que solo entren cadenas, evitando errores en ejecución." },
  { q: "En un examen en papel, ¿qué es lo más importante según el profesor?",
    opts: ["No cometer errores de sintaxis (punto y coma)", "La lógica y el diseño de la jerarquía de clases", "Escribir muy rápido", "Que el código sea muy largo"], ans: 1,
    exp: "La sintaxis es secundaria si la estructura POO y la lógica son correctas." }
];
